(ns fleet.core-test
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [fleet.db :as db]
            [fleet.pin :as pin]
            [fleet.sync :as sync]
            [fleet.west :as west]))

(def fixture
  (str/join "\n"
   ["# west.yml — generated by scripts/gen-west-manifest.cljs. DO NOT EDIT BY HAND."
    "manifest:"
    "  version: \"1.0\""
    ""
    "  remotes:"
    "    - name: kotoba-lang"
    "      url-base: git@github.com:kotoba-lang"
    "    - name: gftdcojp"
    "      url-base: git@github.com:gftdcojp"
    ""
    "  defaults:"
    "    revision: main"
    ""
    "  group-filter: [+kotoba-lang, -datalad, -archived]"
    ""
    "  projects:"
    "    - name: plain"
    "      remote: kotoba-lang"
    "      revision: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "      path: orgs/kotoba-lang/plain"
    "      groups: [kotoba-lang]"
    "    - name: heavy-sub"
    "      remote: kotoba-lang"
    "      revision: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    "      path: orgs/kotoba-lang/heavy-sub"
    "      clone-depth: 1"
    "      groups: [kotoba-lang]"
    "      submodules: true"
    "    - name: annexed"
    "      remote: gftdcojp"
    "      revision: cccccccccccccccccccccccccccccccccccccccc"
    "      path: orgs/gftdcojp/annexed"
    "      groups: [datalad]"
    "      userdata:"
    "        datalad: true"
    "        annex-remote: b2"
    "    - name: retired"
    "      remote: gftdcojp"
    "      revision: dddddddddddddddddddddddddddddddddddddddd"
    "      path: orgs/gftdcojp/retired"
    "      groups: [archived]"
    "      userdata:"
    "        archived: true"
    "    - name: gftdcojp-aliased"
    "      remote: gftdcojp"
    "      repo-path: aliased"
    "      revision: eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
    "      path: orgs/gftdcojp/aliased"
    "      groups: [gftdcojp]"
    ""
    "  self:"
    "    path: manifest"
    "    west-commands: west-commands.yml"
    ""]))

(deftest parse-emit-bijection
  (is (= fixture (west/emit (west/parse fixture)))))

(deftest parse-shapes
  (let [d (west/parse fixture)]
    (testing "entity fields"
      (is (= 5 (count (:fleet/repos d))))
      (is (= {:repo/name "heavy-sub" :repo/remote "kotoba-lang"
              :repo/revision "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
              :repo/path "orgs/kotoba-lang/heavy-sub" :repo/clone-depth 1
              :repo/groups ["kotoba-lang"] :repo/submodules? true}
             (west/find-repo d "heavy-sub")))
      (is (= {:datalad true :annex-remote "b2"}
             (:repo/userdata (west/find-repo d "annexed"))))
      (is (= {:archived true} (:repo/userdata (west/find-repo d "retired"))))
      (is (= "aliased" (:repo/repo-path (west/find-repo d "gftdcojp-aliased")))))
    (testing "remotes + url"
      (is (= "git@github.com:kotoba-lang/plain"
             (west/remote-url d (west/find-repo d "plain"))))
      (is (= "git@github.com:gftdcojp/aliased"
             (west/remote-url d (west/find-repo d "gftdcojp-aliased")))))
    (testing "queries"
      (is (= {:repos 5 :orgs 2 :heavy 1 :datalad 1 :archived 1} (db/stats d)))
      (is (= ["annexed" "retired" "gftdcojp-aliased"]
             (mapv :repo/name (db/by-org d "gftdcojp")))))))

(deftest pin-advance
  (let [d  (west/parse fixture)
        ev (db/pin-advance-event
            [] {:repo "plain"
                :old-rev "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                :new-rev "1111111111111111111111111111111111111111"
                :actor "test" :at "2026-07-16T00:00:00Z"})
        d' (db/apply-pin-advance d ev)]
    (is (= 1 (:event/seq ev)))
    (is (= "1111111111111111111111111111111111111111"
           (:repo/revision (west/find-repo d' "plain"))))
    (testing "projection reflects the advance and nothing else"
      (is (= (str/replace fixture "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                          "1111111111111111111111111111111111111111")
             (west/emit d'))))
    (is (thrown? #?(:clj Exception :cljs js/Error)
                 (db/apply-pin-advance d (assoc ev :repo/name "nope"))))))

(deftest sync-planner
  (let [d (west/parse fixture)
        e (west/find-repo d "plain")]
    (testing "missing dir -> materialize, pinned SHA fetched directly"
      (let [{:keys [action steps]} (sync/plan d e {:exists? false} "/ws/orgs/kotoba-lang/plain")]
        (is (= :materialize action))
        (is (= ["git" "-C" "/ws/orgs/kotoba-lang/plain" "fetch" "--depth" "1" "origin"
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"]
               (nth steps 2)))))
    (testing "dirty checkout is skipped, never overwritten (west semantics)"
      (is (= :skip-dirty (:action (sync/plan d e {:exists? true :dirty? true :head "x"} "/ws/p")))))
    (testing "clean at pin -> noop"
      (is (= :noop (:action (sync/plan d e {:exists? true :dirty? false
                                            :head (:repo/revision e)} "/ws/p")))))
    (testing "clean behind pin -> advance"
      (is (= :advance (:action (sync/plan d e {:exists? true :dirty? false :head "old"} "/ws/p")))))
    (testing "working-set selectors"
      (is (= ["plain" "heavy-sub"]
             (mapv :repo/name (sync/working-set d {:org "kotoba-lang"}))))
      (is (= ["annexed"] (mapv :repo/name (sync/working-set d {:group "datalad"}))))
      (is (= ["retired"] (mapv :repo/name (sync/working-set d {:names ["retired"]})))))))

;; ---------------------------------------------------------------------------
;; Phase 1: signed pin admission gate (pure — fake crypto ports)

(def ^:private fake-hash #(str "H" (count %)))
;; fake signature scheme: sig is valid iff it equals "SIG:" + pubkey + payload hash
(defn- fake-sign [pubkey payload] (str "SIG:" pubkey ":" (fake-hash payload)))
(defn- fake-verify [pubkey payload sig] (= sig (fake-sign pubkey payload)))

(def ^:private keyring
  {:keys {"ed25519:agentA" {:grants #{"orgs/kotoba-lang/*"}}
          "ed25519:agentB" {:grants #{"orgs/gftdcojp/one-repo"}}}})

(defn- proposal [pubkey rec]
  {:record rec :signature (fake-sign pubkey (pin/canonical-str rec)) :signer (str "ed25519:" pubkey)})

(defn- ctx [current & {:as extra}]
  (merge {:repo-path "orgs/kotoba-lang/plain" :current current :keyring keyring
          :verify-fn fake-verify :hash-fn fake-hash :reachable? true}
         extra))

(deftest pin-admission-gate
  (let [genesis (pin/make-record {:repo "plain" :value "aaa" :sequence 1 :parent nil})
        g-prop  (proposal "agentA" genesis)
        g-cur   {:record genesis :signature (:signature g-prop)}
        next-ok (pin/make-record {:repo "plain" :value "bbb" :sequence 2
                                  :parent (pin/record-hash fake-hash genesis (:signature g-prop))})]
    (testing "genesis accept"
      (is (= :accept (:verdict (pin/admit g-prop (ctx nil))))))
    (testing "valid advance accepts"
      (is (= :accept (:verdict (pin/admit (proposal "agentA" next-ok) (ctx g-cur))))))
    (testing "sequence rollback rejected even with a valid signature"
      (let [bad (assoc next-ok :pin/sequence 1)]
        (is (some #{:sequence-rollback}
                  (:reasons (pin/admit (proposal "agentA" bad) (ctx g-cur)))))))
    (testing "parent mismatch (replay) rejected"
      (let [bad (assoc next-ok :pin/parent "H999")]
        (is (some #{:parent-mismatch}
                  (:reasons (pin/admit (proposal "agentA" bad) (ctx g-cur)))))))
    (testing "unauthorized signer rejected (grant does not cover the path)"
      (is (some #{:unauthorized-signer}
                (:reasons (pin/admit (proposal "agentB" next-ok) (ctx g-cur))))))
    (testing "tampered record fails signature"
      (let [p (proposal "agentA" next-ok)
            tampered (assoc-in p [:record :pin/value] "evil")]
        (is (some #{:bad-signature}
                  (:reasons (pin/admit tampered (ctx g-cur)))))))
    (testing "unreachable pin rejected; unverifiable warn-accepts (fail-open)"
      (is (some #{:unreachable-from-upstream-default-branch}
                (:reasons (pin/admit (proposal "agentA" next-ok) (ctx g-cur :reachable? false)))))
      (is (= :warn-accept
             (:verdict (pin/admit (proposal "agentA" next-ok) (ctx g-cur :reachable? :unknown))))))
    (testing "grant wildcard semantics"
      (is (pin/authorized? keyring "ed25519:agentA" "orgs/kotoba-lang/anything"))
      (is (not (pin/authorized? keyring "ed25519:agentA" "orgs/gftdcojp/x")))
      (is (pin/authorized? keyring "ed25519:agentB" "orgs/gftdcojp/one-repo")))))

(deftest pin-value-regression
  (let [genesis (pin/make-record {:repo "plain" :value "new" :sequence 1 :parent nil})
        g-prop  (proposal "agentA" genesis)
        g-cur   {:record genesis :signature (:signature g-prop)}
        back    (pin/make-record {:repo "plain" :value "old" :sequence 2
                                  :parent (pin/record-hash fake-hash genesis (:signature g-prop))})]
    (testing "value regression rejected even with valid signature + advancing sequence"
      (is (= {:verdict :reject :reasons [:value-regression]}
             (pin/admit (proposal "agentA" back) (ctx g-cur :value-advance? false)))))
    (testing "unverifiable value-advance warn-accepts (fail-open, like Rule 2 repair path)"
      (is (= :warn-accept
             (:verdict (pin/admit (proposal "agentA" back) (ctx g-cur :value-advance? :unknown))))))
    (testing "genesis ignores value-advance"
      (is (= :accept (:verdict (pin/admit g-prop (ctx nil :value-advance? true))))))))
